### PR TITLE
Fix examples

### LINKED ISSUE #14: TypeError: Cannot read property 'passesHashCheck' of undefined
I am facing the following issue on the download script.

`/home/testbed/Downloads/btcash/download.js:14`
if(result.passesHashCheck){
          ^

TypeError: Cannot read property 'passesHashCheck' of undefined
    at Object.<anonymous> (/home/testbed/Downloads/btcash/download.js:14:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at `internal/main/run_main_module.js:17:47`

error_passeshashcheck

### PR DESCRIPTION
**Pull request by DesWurstes**
Also you might need to change the unpkg [link](https://github.com/simpleledgerinc/grpc-bchrpc-web#install) here to `https://unpkg.com/grpc-bchrpc-web`

Resolves #14

### CODE REVIEW

**Review by jcramer — COMMENTED** [review]
It seems like these changes would break the legacy version.  Can we add some tests to prove old behavior still works?

**Comment by DesWurstes** [comment]
Hello, I have added a test `npm run test`.

**Comment by jcramer** [comment]
Sure, what's the txid for Mario.png?

**Comment by DesWurstes** [comment]
Hello, everything is ready now, the test uses the original test transaction in the current README.md

There are three commits, please review commit by commit, the last one was automatically made with the Atom editor so that I can then use it to produce the next pull request instead of Notepad.

**Review by jcramer — CHANGES_REQUESTED** [review]
`npm test` is failing for me after clean `npm i`.  Observations:

1) `mocharc.yml` should be named `.mocharc.yml`
2) update mocha to latest version, 8.3.2
3) add ts-node and source-map-support as dev deps

After I did these things the tests ran, but the test doesn't pass.

**Comment by DesWurstes** [comment]
Hello, there should be no modifications necessary. After freshly cloning, `npm i && npm run build || npm run test` works for me. The test passes for me under 2 seconds and there is 5 seconds timeout. Do you have a slow internet connection? Does it timeout or show an error or any console output? It works for me on both macOS and Linux.

**Comment by jcramer** [comment]
I see. I wasn't aware there was a build step needed.  Maybe the build step should be part of the test command?

I ran the test and it passed, yay!  I'll take a closer look later tonight and do a merge.

**Comment by jcramer** [comment]
Your test and updates have been merged.  I added a regtest setup with a test for upload/download file type 0x01.  When you have a chance please review and add similar thing for the 0x02 file type you are working on.

**Pull request merged**
